# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'

target 'RNfirechat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNfirechat

  target 'RNfirechat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNfirechatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
